myList=['Spain', 'Italy', 'Cuba', 'Hawaii', 'USA']
print(myList)
print(sorted(myList))
print(myList)
testList=sorted(myList, reverse=True)
print(testList)
print(myList)
myList.reverse()
print(myList)
myList.reverse()
print(myList)
myList.sort()
print(myList)
myList.sort(reverse=True)
print(myList)
